#!/bin/bash

PATH_TO_FX=/usr/local/lib/jvm/openjfx/javafx-sdk-21.0.7/lib
PATH_TO_JAR=target/wordle-1.0-SNAPSHOT.jar

java --module-path $PATH_TO_FX --add-modules javafx.controls,javafx.fxml -jar $PATH_TO_JAR
